### ISSUE TITLE
Instaloader is terminated with HTTP 502 error

### ISSUE THREAD

**Issue by duke8585** [Thammus/instaloader#60] opened 2017-12-12 08:56 UTC
Starting instaloader with the following arguments:
`instaloader "#selfie" --only-if="not is_video" --filename-pattern={date:%H:%M:%S}_-_{profile} --count 55`
but also in the most simplistic form:

`instaloader "#lol" `

will yield the following error message:

```
JSON Query to graphql/query: HTTP error code 502. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 502. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 502.

Errors occured:
JSON Query to graphql/query: HTTP error code 502.
```

Also, adding --no-geotags or --no-captions won´t help. A week ago, instaloader did not produce this error with any argument-variations. Nothing besides the system (OSX) was modified since then.

**Comment by aandergr** [comment] 2017-12-12 09:01
Might be a duplicate of #59, which has been fixed yesterday. Are you running the latest version of Instaloader, 3.2.1?

**Comment by duke8585** [comment] 2017-12-12 09:06
thanks a lot, updating it did the trick.

**Closed** 2017-12-12 09:13 UTC
Labels: duplicate
