### ISSUE TITLE
Not downloading all posts with a certain hashtag

### ISSUE THREAD

**Issue by aatclv** [Thammus/instaloader#55] opened 2017-11-09 15:02 UTC
When the search by hashtag retrieves a high number of results (> 1000 for example), not all posts are downloaded (and no error in printed).

**Comment by aandergr** [comment] 2017-11-09 17:44
On the first glance, this seems a duplicate of #20.

The number of posts with a certain hashtag may differ from the number of posts that can actually be accessed, as the hashtag count might include private posts. The more interesting question is whether an official Instagram app loads more hashtags posts than Instaloader does.

Are the "missing" posts accessible by other Instagram clients, such as the browser interface or the Instagram App?

**Closed** 2017-11-17 09:14 UTC
Labels: duplicate
