### ISSUE TITLE
Instaloader hashtag results differ from what Instagram actually shows

### ISSUE THREAD

**Issue by AriaShishegaran** [Thammus/instaloader#34] opened 2017-08-12 22:19 UTC
when i search hashtags in instaloader the number of results received differ from what instagram actually shows:
https://www.instagram.com/explore/tags/salam/
```instaloader "#salam"```

UPDATE: my terminal took a persian character and turned it into an arabic one (they look the same but different in encoding) and that was why i received the previous results on persian language. what i do now is that i type my text inside a browser and then paste it into terminal...

**Comment by MatthieuBonenfant** [comment] 2017-08-13 01:02
I tried #zyng and just by looking at the 4 first images found, instaloader found one extra image that does not show up when I search online... which is that one
https://www.instagram.com/p/BXsUTNenVQE/

valleyoilersWhen you worked overtime on third shift and going to an oily event this is what you drink to get your natural energy. #YoungLiving #Zyng #Nitro #ValleyOilers##ILoveMyEssentialOils
oilydropperSee you soon with lots of zyng

The difference I see compared to the other ones is the use of a capital letter in the extra image instaloader found, but instagram appear to hide it when searching for either 
https://www.instagram.com/explore/tags/Zyng/
or https://www.instagram.com/explore/tags/zyng/

Could that just be it?

**Comment by AriaShishegaran** [comment] 2017-08-13 12:35
@MatthieuBonenfant yes but please try this as well, this is in Persian:
https://www.instagram.com/explore/tags/%D8%B2%DB%8C%D9%86%DA%AF/
you see that there 54 results shown but when i type the hashtag inside instaloader ```#زینگ``` the results are different, the same also happens for English scenarios like the hashtag i mentioned above.

**Comment by MatthieuBonenfant** [comment] 2017-08-14 04:09
Sorry but I don't know how to use Arabic characters in windows command line / batch files.

**Comment by AriaShishegaran** [comment] 2017-08-14 09:22
i can help you debug RTL characters, or i can send you the complete commands you might need, the problem in the end is not with Persian character but with the logic of how the scripts results differ from the actual.

**Comment by AriaShishegaran** [comment] 2017-08-19 16:25
@Thammus any comment on this?

**Comment by aandergr** [comment] 2017-08-19 16:41
I think this might be a duplicate of #20. The number of posts with a certain hashtag may differ from the number of posts which can actually be accessed, as the hashtag count might include private posts. The more interesting question is whether an official Instagram app loads more hashtags posts than Instaloader does.

Hashtags should not be case-sensitive. With 9ee98a2, Instaloader uses all-lowercase strings for both hashtags and usernames.

Trying to push issues by adding comments not containing any valuable content is considered an unwelcome practice here - on this project, and on free software projects in general. The issue trackers distinguish between open and closed issues. Issues remain open until they can safely be considered solved. Even if an issue is closed accidentally or inappropriately, everyone is free to reopen them. We can easily get an overview about yet-unresolved issues and always see them, whether they are active or not. It is rather annoying to get a notification even though there is nothing new, and it is in no way motivating us to prioritize particular issues.

**Comment by AriaShishegaran** [comment] 2017-08-19 16:46
well noted, i completely understand and of course i'm not trying to annoy anyone here or anywhere else, i apologize and thank you for this project and all the efforts you are putting into it.

**Comment by aandergr** [comment] 2017-08-31 08:40
> UPDATE: my terminal took a persian character and turned it into an arabic one (they look the same but different in encoding) and that was why i received the previous results on persian language. what i do now is that i type my text inside a browser and then paste it into terminal...

I guess this justifies closing the issue.

**Closed by aandergr** 2017-08-31 08:40 UTC
